name: Deploy Test Environment

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      project_name: webstrom-test
      backend_port: '8920'
      static_port: '8921'
      django_settings_module: 'webstrom.settings_test'
      media_path: '/data/www/webstrom-test'
    secrets:
      ssh_private_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PRIVATE_KEY }}
